[package]
name = "web-assets"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mime = "0.3.0"