/*!
# Web Assets

Static assets for LumosAI UI components including CSS, JavaScript, and images.
*/

pub mod files {
    //! Static file definitions

    pub struct StaticFile {
        pub name: &'static str,
        pub content: &'static [u8],
        pub mime_type: &'static str,
    }

    // Placeholder for static files - in a real implementation,
    // these would be generated by a build script or included via include_bytes!

    // Core assets
    pub const collapse_svg: StaticFile = StaticFile {
        name: "collapse.svg",
        content: b"<svg><!-- collapse icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const index_css: StaticFile = StaticFile {
        name: "index.css",
        content: b"/* LumosAI UI styles */",
        mime_type: "text/css",
    };

    pub const output_css: StaticFile = StaticFile {
        name: "output.css",
        content: b"/* Tailwind CSS output */",
        mime_type: "text/css",
    };

    pub const index_js: StaticFile = StaticFile {
        name: "index.js",
        content: b"// LumosAI UI JavaScript",
        mime_type: "application/javascript",
    };

    pub const bionic_logo_svg: StaticFile = StaticFile {
        name: "bionic-logo.svg",
        content: b"<svg><!-- logo --></svg>",
        mime_type: "image/svg+xml",
    };

    // Navigation icons
    pub const nav_service_requests_svg: StaticFile = StaticFile {
        name: "nav-service-requests.svg",
        content: b"<svg><!-- service requests icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const nav_history_svg: StaticFile = StaticFile {
        name: "nav-history.svg",
        content: b"<svg><!-- history icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const assistant_svg: StaticFile = StaticFile {
        name: "assistant.svg",
        content: b"<svg><!-- assistant icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const nav_audit_svg: StaticFile = StaticFile {
        name: "nav-audit.svg",
        content: b"<svg><!-- audit icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const nav_ccsds_data_svg: StaticFile = StaticFile {
        name: "nav-ccsds-data.svg",
        content: b"<svg><!-- data icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const nav_api_keys_svg: StaticFile = StaticFile {
        name: "nav-api-keys.svg",
        content: b"<svg><!-- api keys icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const nav_members_svg: StaticFile = StaticFile {
        name: "nav-members.svg",
        content: b"<svg><!-- members icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const nav_teams_svg: StaticFile = StaticFile {
        name: "nav-teams.svg",
        content: b"<svg><!-- teams icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const nav_phonebook_svg: StaticFile = StaticFile {
        name: "nav-phonebook.svg",
        content: b"<svg><!-- phonebook icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const limits_svg: StaticFile = StaticFile {
        name: "limits.svg",
        content: b"<svg><!-- limits icon --></svg>",
        mime_type: "image/svg+xml",
    };

    // Button icons
    pub const button_plus_svg: StaticFile = StaticFile {
        name: "button-plus.svg",
        content: b"<svg><!-- plus button icon --></svg>",
        mime_type: "image/svg+xml",
    };

    // Legacy compatibility
    pub const COLLAPSE_SVG: StaticFile = collapse_svg;
}
