/*!
# Web Assets

Static assets for LumosAI UI components including CSS, JavaScript, and images.
*/

pub mod files {
    //! Static file definitions

    pub struct StaticFile {
        pub name: &'static str,
        pub content: &'static [u8],
        pub mime_type: &'static str,
    }

    // Placeholder for static files - in a real implementation,
    // these would be generated by a build script or included via include_bytes!

    // Core assets
    pub const COLLAPSE_SVG: StaticFile = StaticFile {
        name: "collapse.svg",
        content: b"<svg><!-- collapse icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const INDEX_CSS: StaticFile = StaticFile {
        name: "index.css",
        content: include_bytes!("input.css"),
        mime_type: "text/css",
    };

    pub const OUTPUT_CSS: StaticFile = StaticFile {
        name: "output.css",
        content: b"/* LumosAI UI Custom Styles */

/* Base layout styles */
.sidebar {
    background-color: hsl(var(--b2));
    border-right: 1px solid hsl(var(--b3));
}

.main-content {
    background-color: hsl(var(--b1));
    flex: 1;
}

/* Enhanced card styles */
.card {
    background-color: hsl(var(--b1));
    border: 1px solid hsl(var(--b3));
    border-radius: 0.5rem;
    box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
}

.card-header {
    border-bottom: 1px solid hsl(var(--b3));
    padding: 1rem;
    font-weight: 600;
}

.card-body {
    padding: 1rem;
}

/* Enhanced button styles */
.btn {
    padding: 0.5rem 1rem;
    border-radius: 0.375rem;
    font-weight: 500;
    transition: all 0.2s;
    border: none;
    cursor: pointer;
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
}

.btn:hover {
    transform: translateY(-1px);
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

.btn-primary {
    background-color: hsl(var(--p));
    color: hsl(var(--pc));
}

.btn-primary:hover {
    background-color: hsl(var(--p) / 0.9);
}

.btn-secondary {
    background-color: hsl(var(--s));
    color: hsl(var(--sc));
}

.btn-ghost {
    background-color: transparent;
    color: hsl(var(--bc));
}

.btn-ghost:hover {
    background-color: hsl(var(--b3));
}

/* Enhanced menu styles */
.menu {
    padding: 0.5rem;
}

.menu li {
    margin-bottom: 0.25rem;
}

.menu li a {
    display: flex;
    align-items: center;
    padding: 0.75rem 1rem;
    color: hsl(var(--bc));
    text-decoration: none;
    border-radius: 0.375rem;
    transition: all 0.2s;
}

.menu li a:hover {
    background-color: hsl(var(--b3));
    transform: translateX(4px);
}

.menu li a.active {
    background-color: hsl(var(--p));
    color: hsl(var(--pc));
    font-weight: 600;
}

/* Enhanced form styles */
.input, .textarea, .select {
    width: 100%;
    padding: 0.75rem;
    border: 1px solid hsl(var(--b3));
    border-radius: 0.375rem;
    background-color: hsl(var(--b1));
    color: hsl(var(--bc));
    transition: all 0.2s;
}

.input:focus, .textarea:focus, .select:focus {
    outline: none;
    border-color: hsl(var(--p));
    box-shadow: 0 0 0 3px hsl(var(--p) / 0.1);
}

.textarea {
    resize: vertical;
    min-height: 4rem;
}

/* Chat styles */
.chat-container {
    display: flex;
    flex-direction: column;
    height: 100%;
}

.chat-messages {
    flex: 1;
    overflow-y: auto;
    padding: 1rem;
    display: flex;
    flex-direction: column;
    gap: 1rem;
}

.chat-input {
    border-top: 1px solid hsl(var(--b3));
    padding: 1rem;
    background-color: hsl(var(--b1));
}

/* Message styles */
.message {
    display: flex;
    gap: 0.75rem;
    max-width: 80%;
}

.message.user {
    flex-direction: row-reverse;
    margin-left: auto;
}

.message-content {
    padding: 0.75rem 1rem;
    border-radius: 1rem;
    word-wrap: break-word;
}

.message.user .message-content {
    background-color: hsl(var(--p));
    color: hsl(var(--pc));
    border-bottom-right-radius: 0.25rem;
}

.message.assistant .message-content {
    background-color: hsl(var(--b2));
    color: hsl(var(--bc));
    border-bottom-left-radius: 0.25rem;
}

/* Dashboard styles */
.dashboard-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 1.5rem;
    padding: 1rem;
}

.stat-card {
    background-color: hsl(var(--b1));
    border: 1px solid hsl(var(--b3));
    border-radius: 0.5rem;
    padding: 1.5rem;
    transition: all 0.2s;
}

.stat-card:hover {
    transform: translateY(-2px);
    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
}

.stat-value {
    font-size: 2rem;
    font-weight: bold;
    color: hsl(var(--bc));
    margin-bottom: 0.5rem;
}

.stat-title {
    font-size: 0.875rem;
    color: hsl(var(--bc) / 0.7);
    text-transform: uppercase;
    letter-spacing: 0.05em;
}

/* Loading and status indicators */
.loading {
    display: inline-block;
    width: 1rem;
    height: 1rem;
    border: 2px solid hsl(var(--b3));
    border-radius: 50%;
    border-top-color: hsl(var(--p));
    animation: spin 1s ease-in-out infinite;
}

@keyframes spin {
    to { transform: rotate(360deg); }
}

/* Responsive utilities */
@media (max-width: 768px) {
    .sidebar {
        position: fixed;
        top: 0;
        left: 0;
        bottom: 0;
        width: 16rem;
        transform: translateX(-100%);
        transition: transform 0.3s ease;
        z-index: 50;
    }

    .sidebar.open {
        transform: translateX(0);
    }

    .dashboard-grid {
        grid-template-columns: 1fr;
    }

    .message {
        max-width: 95%;
    }
}

/* Utility classes */
.text-center { text-align: center; }
.text-left { text-align: left; }
.text-right { text-align: right; }
.font-bold { font-weight: bold; }
.font-medium { font-weight: 500; }
.text-sm { font-size: 0.875rem; }
.text-xs { font-size: 0.75rem; }
.text-lg { font-size: 1.125rem; }
.text-xl { font-size: 1.25rem; }
.text-2xl { font-size: 1.5rem; }
.text-3xl { font-size: 1.875rem; }
.mb-2 { margin-bottom: 0.5rem; }
.mb-4 { margin-bottom: 1rem; }
.mt-2 { margin-top: 0.5rem; }
.mt-4 { margin-top: 1rem; }
.p-2 { padding: 0.5rem; }
.p-4 { padding: 1rem; }
.px-4 { padding-left: 1rem; padding-right: 1rem; }
.py-2 { padding-top: 0.5rem; padding-bottom: 0.5rem; }
.flex { display: flex; }
.flex-col { flex-direction: column; }
.items-center { align-items: center; }
.justify-center { justify-content: center; }
.justify-between { justify-content: space-between; }
.gap-2 { gap: 0.5rem; }
.gap-4 { gap: 1rem; }
.w-full { width: 100%; }
.h-full { height: 100%; }
.rounded { border-radius: 0.25rem; }
.rounded-lg { border-radius: 0.5rem; }
.shadow { box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1); }
.shadow-lg { box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1); }
",
        mime_type: "text/css",
    };

    pub const INDEX_JS: StaticFile = StaticFile {
        name: "index.js",
        content: b"// LumosAI UI JavaScript",
        mime_type: "application/javascript",
    };

    pub const BIONIC_LOGO_SVG: StaticFile = StaticFile {
        name: "bionic-logo.svg",
        content: b"<svg><!-- logo --></svg>",
        mime_type: "image/svg+xml",
    };

    // Navigation icons
    pub const NAV_SERVICE_REQUESTS_SVG: StaticFile = StaticFile {
        name: "nav-service-requests.svg",
        content: b"<svg><!-- service requests icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const NAV_HISTORY_SVG: StaticFile = StaticFile {
        name: "nav-history.svg",
        content: b"<svg><!-- history icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const ASSISTANT_SVG: StaticFile = StaticFile {
        name: "assistant.svg",
        content: b"<svg><!-- assistant icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const NAV_AUDIT_SVG: StaticFile = StaticFile {
        name: "nav-audit.svg",
        content: b"<svg><!-- audit icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const NAV_CCSDS_DATA_SVG: StaticFile = StaticFile {
        name: "nav-ccsds-data.svg",
        content: b"<svg><!-- data icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const NAV_API_KEYS_SVG: StaticFile = StaticFile {
        name: "nav-api-keys.svg",
        content: b"<svg><!-- api keys icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const NAV_MEMBERS_SVG: StaticFile = StaticFile {
        name: "nav-members.svg",
        content: b"<svg><!-- members icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const NAV_TEAMS_SVG: StaticFile = StaticFile {
        name: "nav-teams.svg",
        content: b"<svg><!-- teams icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const NAV_PHONEBOOK_SVG: StaticFile = StaticFile {
        name: "nav-phonebook.svg",
        content: b"<svg><!-- phonebook icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const LIMITS_SVG: StaticFile = StaticFile {
        name: "limits.svg",
        content: b"<svg><!-- limits icon --></svg>",
        mime_type: "image/svg+xml",
    };

    // Button and action icons
    pub const BUTTON_PLUS_SVG: StaticFile = StaticFile {
        name: "button-plus.svg",
        content: b"<svg><!-- plus button icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const DELETE_SVG: StaticFile = StaticFile {
        name: "delete.svg",
        content: b"<svg><!-- delete icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const SPINNER_SVG: StaticFile = StaticFile {
        name: "spinner.svg",
        content: b"<svg><!-- spinner icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const TOOLS_SVG: StaticFile = StaticFile {
        name: "tools.svg",
        content: b"<svg><!-- tools icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const HANDSHAKE_SVG: StaticFile = StaticFile {
        name: "handshake.svg",
        content: b"<svg><!-- handshake icon --></svg>",
        mime_type: "image/svg+xml",
    };

    // Audio control icons
    pub const READ_ALOUD_LOADING_SVG: StaticFile = StaticFile {
        name: "read-aloud-loading.svg",
        content: b"<svg><!-- read aloud loading icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const READ_ALOUD_STOP_SVG: StaticFile = StaticFile {
        name: "read-aloud-stop.svg",
        content: b"<svg><!-- read aloud stop icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const READ_ALOUD_SVG: StaticFile = StaticFile {
        name: "read-aloud.svg",
        content: b"<svg><!-- read aloud icon --></svg>",
        mime_type: "image/svg+xml",
    };

    // Copy and interaction icons
    pub const TICK_COPY_SVG: StaticFile = StaticFile {
        name: "tick-copy.svg",
        content: b"<svg><!-- tick copy icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const COPY_SVG: StaticFile = StaticFile {
        name: "copy.svg",
        content: b"<svg><!-- copy icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const PROFILE_SVG: StaticFile = StaticFile {
        name: "profile.svg",
        content: b"<svg><!-- profile icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const AI_SVG: StaticFile = StaticFile {
        name: "ai.svg",
        content: b"<svg><!-- ai icon --></svg>",
        mime_type: "image/svg+xml",
    };

    // Input control icons
    pub const MICROPHONE_SVG: StaticFile = StaticFile {
        name: "microphone.svg",
        content: b"<svg><!-- microphone icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const STOP_RECORDING_SVG: StaticFile = StaticFile {
        name: "stop-recording.svg",
        content: b"<svg><!-- stop recording icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const ATTACH_SVG: StaticFile = StaticFile {
        name: "attach.svg",
        content: b"<svg><!-- attach icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const STREAMING_STOP_SVG: StaticFile = StaticFile {
        name: "streaming-stop.svg",
        content: b"<svg><!-- streaming stop icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const SUBMIT_BUTTON_SVG: StaticFile = StaticFile {
        name: "submit-button.svg",
        content: b"<svg><!-- submit button icon --></svg>",
        mime_type: "image/svg+xml",
    };

    // Additional icons for compatibility
    pub const BUTTON_SELECT_SVG: StaticFile = StaticFile {
        name: "button-select.svg",
        content: b"<svg><!-- select button icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const BUTTON_EDIT_SVG: StaticFile = StaticFile {
        name: "button-edit.svg",
        content: b"<svg><!-- edit button icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const MENU_DELETE_SVG: StaticFile = StaticFile {
        name: "menu-delete.svg",
        content: b"<svg><!-- menu delete icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const EMPTY_API_KEYS_SVG: StaticFile = StaticFile {
        name: "empty-api-keys.svg",
        content: b"<svg><!-- empty api keys icon --></svg>",
        mime_type: "image/svg+xml",
    };

    pub const AVATAR_SVG: StaticFile = StaticFile {
        name: "avatar.svg",
        content: b"<svg><!-- avatar icon --></svg>",
        mime_type: "image/svg+xml",
    };

    // Legacy compatibility aliases - keep for backward compatibility
    #[allow(non_upper_case_globals)]
    pub const collapse_svg: StaticFile = COLLAPSE_SVG;
    #[allow(non_upper_case_globals)]
    pub const index_css: StaticFile = INDEX_CSS;
    #[allow(non_upper_case_globals)]
    pub const output_css: StaticFile = OUTPUT_CSS;
    #[allow(non_upper_case_globals)]
    pub const index_js: StaticFile = INDEX_JS;
    #[allow(non_upper_case_globals)]
    pub const bionic_logo_svg: StaticFile = BIONIC_LOGO_SVG;
    #[allow(non_upper_case_globals)]
    pub const nav_service_requests_svg: StaticFile = NAV_SERVICE_REQUESTS_SVG;
    #[allow(non_upper_case_globals)]
    pub const nav_history_svg: StaticFile = NAV_HISTORY_SVG;
    #[allow(non_upper_case_globals)]
    pub const assistant_svg: StaticFile = ASSISTANT_SVG;
    #[allow(non_upper_case_globals)]
    pub const nav_audit_svg: StaticFile = NAV_AUDIT_SVG;
    #[allow(non_upper_case_globals)]
    pub const nav_ccsds_data_svg: StaticFile = NAV_CCSDS_DATA_SVG;
    #[allow(non_upper_case_globals)]
    pub const nav_api_keys_svg: StaticFile = NAV_API_KEYS_SVG;
    #[allow(non_upper_case_globals)]
    pub const nav_members_svg: StaticFile = NAV_MEMBERS_SVG;
    #[allow(non_upper_case_globals)]
    pub const nav_teams_svg: StaticFile = NAV_TEAMS_SVG;
    #[allow(non_upper_case_globals)]
    pub const nav_phonebook_svg: StaticFile = NAV_PHONEBOOK_SVG;
    #[allow(non_upper_case_globals)]
    pub const limits_svg: StaticFile = LIMITS_SVG;
    #[allow(non_upper_case_globals)]
    pub const button_plus_svg: StaticFile = BUTTON_PLUS_SVG;
    #[allow(non_upper_case_globals)]
    pub const delete_svg: StaticFile = DELETE_SVG;
    #[allow(non_upper_case_globals)]
    pub const spinner_svg: StaticFile = SPINNER_SVG;
    #[allow(non_upper_case_globals)]
    pub const tools_svg: StaticFile = TOOLS_SVG;
    #[allow(non_upper_case_globals)]
    pub const handshake_svg: StaticFile = HANDSHAKE_SVG;
    #[allow(non_upper_case_globals)]
    pub const read_aloud_loading_svg: StaticFile = READ_ALOUD_LOADING_SVG;
    #[allow(non_upper_case_globals)]
    pub const read_aloud_stop_svg: StaticFile = READ_ALOUD_STOP_SVG;
    #[allow(non_upper_case_globals)]
    pub const read_aloud_svg: StaticFile = READ_ALOUD_SVG;
    #[allow(non_upper_case_globals)]
    pub const tick_copy_svg: StaticFile = TICK_COPY_SVG;
    #[allow(non_upper_case_globals)]
    pub const copy_svg: StaticFile = COPY_SVG;
    #[allow(non_upper_case_globals)]
    pub const profile_svg: StaticFile = PROFILE_SVG;
    #[allow(non_upper_case_globals)]
    pub const ai_svg: StaticFile = AI_SVG;
    #[allow(non_upper_case_globals)]
    pub const microphone_svg: StaticFile = MICROPHONE_SVG;
    #[allow(non_upper_case_globals)]
    pub const stop_recording_svg: StaticFile = STOP_RECORDING_SVG;
    #[allow(non_upper_case_globals)]
    pub const attach_svg: StaticFile = ATTACH_SVG;
    #[allow(non_upper_case_globals)]
    pub const streaming_stop_svg: StaticFile = STREAMING_STOP_SVG;
    #[allow(non_upper_case_globals)]
    pub const submit_button_svg: StaticFile = SUBMIT_BUTTON_SVG;
    #[allow(non_upper_case_globals)]
    pub const button_select_svg: StaticFile = BUTTON_SELECT_SVG;
    #[allow(non_upper_case_globals)]
    pub const button_edit_svg: StaticFile = BUTTON_EDIT_SVG;
    #[allow(non_upper_case_globals)]
    pub const menu_delete_svg: StaticFile = MENU_DELETE_SVG;
    #[allow(non_upper_case_globals)]
    pub const empty_api_keys_svg: StaticFile = EMPTY_API_KEYS_SVG;
    #[allow(non_upper_case_globals)]
    pub const avatar_svg: StaticFile = AVATAR_SVG;
}
