[test]
# 测试配置
coverage = true
showAllErrors = true

[build]
# 构建配置
minify = true
sourcemap = "external"
target = "browser"
externals = []

[install]
# 安装依赖配置
production = false
exact = true
optional = false
dev = true

[install.cache]
# 缓存配置
dir = ".bun"
disable = false 