[package]
name = "lumosai-vector-milvus"
version = "0.1.4"
edition = "2021"
authors = ["LumosAI Team <team@lumosai.dev>"]
description = "Milvus integration for LumosAI vector storage - high-performance vector database"
license = "MIT"
repository = "https://github.com/louloulin/lumos.ai.git"
homepage = "https://lumosai.dev"
documentation = "https://docs.rs/lumosai-vector-milvus"
readme = "README.md"
keywords = ["ai", "vector", "database", "milvus", "search"]
categories = ["database", "science", "api-bindings"]

[dependencies]
# Core dependencies
lumosai-vector-core = { path = "../core", version = "0.1.0", features = ["serde"] }
async-trait = "0.1.77"
tokio = { version = "1.35", features = ["full"] }

# HTTP client for Milvus REST API
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling and logging
thiserror = "1.0"
tracing = "0.1"
anyhow = "1.0"

# Utilities
uuid = { version = "1.6", features = ["v4", "serde"] }
futures = "0.3"
base64 = "0.21"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.8"
env_logger = "0.10"
wiremock = "0.5"

[features]
default = []
# Enable all features
all = ["metrics", "auth"]
# Enable metrics collection
metrics = []
# Enable authentication features
auth = []

[[example]]
name = "milvus_basic_usage"
required-features = []

[[example]]
name = "milvus_batch_operations"
required-features = []



[[example]]
name = "milvus_collection_management"
required-features = []
