name = "test-project"
version = "0.1.0"
authors = []
license = "MIT"
tools = []

[dependencies]

[dev_dependencies]

[build]
target = "release"
optimization = "speed"
features = []
exclude = []

[deployment.platforms]

[deployment.environment]
